/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TectonicCoreStorage__factory } from "./TectonicCoreStorage__factory";
export { TectonicCoreV1Storage__factory } from "./TectonicCoreV1Storage__factory";
export { TectonicCoreV2Storage__factory } from "./TectonicCoreV2Storage__factory";
export { TectonicCoreV3Storage__factory } from "./TectonicCoreV3Storage__factory";
export { TectonicCoreV4Storage__factory } from "./TectonicCoreV4Storage__factory";
export { TectonicCoreV5Storage__factory } from "./TectonicCoreV5Storage__factory";
export { TectonicCoreV6Storage__factory } from "./TectonicCoreV6Storage__factory";
export { TectonicSocketAdminStorage__factory } from "./TectonicSocketAdminStorage__factory";
