/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TectonicCoreV1Storage,
  TectonicCoreV1StorageInterface,
} from "../../../../contracts/tectonic/TectonicCoreStorage.sol/TectonicCoreV1Storage";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "accountAssets",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "closeFactorMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "liquidationIncentiveMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "maxAssets",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "oracle",
    outputs: [
      {
        internalType: "contract PriceOracle",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "pendingAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "pendingTectonicCoreImplementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "tectonicCoreImplementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101f9806100206000396000f3fe608060405234801561001057600080fd5b50600436106100935760003560e01c80637dc0d1d0116100665780637dc0d1d0146100e657806394b2294b146100ee578063dce15449146100f6578063e875544614610122578063f851a4401461012a57610093565b80630b2efed61461009857806326782247146100bc5780634ada90af146100c45780637404e92c146100de575b600080fd5b6100a0610132565b604080516001600160a01b039092168252519081900360200190f35b6100a0610141565b6100cc610150565b60408051918252519081900360200190f35b6100a0610156565b6100a0610165565b6100cc610174565b6100a06004803603604081101561010c57600080fd5b506001600160a01b03813516906020013561017a565b6100cc6101af565b6100a06101b5565b6003546001600160a01b031681565b6001546001600160a01b031681565b60065481565b6002546001600160a01b031681565b6004546001600160a01b031681565b60075481565b6008602052816000526040600020818154811061019357fe5b6000918252602090912001546001600160a01b03169150829050565b60055481565b6000546001600160a01b03168156fea265627a7a7231582087db9df8b88c7744afafe50f19fbc70e53ef0543966f7ed50be4dfc35fff5d1664736f6c63430005100032";

type TectonicCoreV1StorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TectonicCoreV1StorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TectonicCoreV1Storage__factory extends ContractFactory {
  constructor(...args: TectonicCoreV1StorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TectonicCoreV1Storage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TectonicCoreV1Storage__factory {
    return super.connect(runner) as TectonicCoreV1Storage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TectonicCoreV1StorageInterface {
    return new Interface(_abi) as TectonicCoreV1StorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TectonicCoreV1Storage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TectonicCoreV1Storage;
  }
}
