/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TectonicSocketInterface,
  TectonicSocketInterfaceInterface,
} from "../../../contracts/tectonic/TectonicSocketInterface";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "_acceptImplementation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TectonicSocketInterface__factory {
  static readonly abi = _abi;
  static createInterface(): TectonicSocketInterfaceInterface {
    return new Interface(_abi) as TectonicSocketInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TectonicSocketInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TectonicSocketInterface;
  }
}
