/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TectonicCoreTest,
  TectonicCoreTestInterface,
} from "../../../contracts/tectonic/TectonicCoreTest";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "ping",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607f8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80635c36b18614602d575b600080fd5b60336045565b60408051918252519081900360200190f35b60019056fea265627a7a72315820b91cef4dab728a732854dd8e336edcb25833b13504fde41b9430e8af66c7404f64736f6c63430005100032";

type TectonicCoreTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TectonicCoreTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TectonicCoreTest__factory extends ContractFactory {
  constructor(...args: TectonicCoreTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TectonicCoreTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TectonicCoreTest__factory {
    return super.connect(runner) as TectonicCoreTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TectonicCoreTestInterface {
    return new Interface(_abi) as TectonicCoreTestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TectonicCoreTest {
    return new Contract(address, _abi, runner) as unknown as TectonicCoreTest;
  }
}
