/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TectonicCoreImplInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_become"
      | "_borrowGuardianPaused"
      | "_grantTonic"
      | "_mintGuardianPaused"
      | "_setBorrowPaused"
      | "_setCloseFactor"
      | "_setCollateralFactor"
      | "_setContributorTonicSpeed"
      | "_setLiquidationIncentive"
      | "_setMintPaused"
      | "_setPauseGuardian"
      | "_setPriceOracle"
      | "_setSeizePaused"
      | "_setTonicSpeed"
      | "_setTransferPaused"
      | "_setWhitelistProtect"
      | "_supportMarket"
      | "accountAssets"
      | "admin"
      | "allMarkets"
      | "borrowAllowed"
      | "borrowCapGuardian"
      | "borrowCaps"
      | "borrowGuardianPaused"
      | "borrowVerify"
      | "checkMembership"
      | "claimTonic(address[],address[],bool,bool)"
      | "claimTonic(address)"
      | "claimTonic(address,address[])"
      | "closeFactorMantissa"
      | "enterMarkets"
      | "exitMarket"
      | "getAllMarkets"
      | "getAssetsIn"
      | "getBlockNumber"
      | "getTonicAddress"
      | "isDeprecated"
      | "isTectonicCore"
      | "lastContributorBlock"
      | "liquidateBorrowAllowed"
      | "liquidateBorrowVerify"
      | "liquidateCalculateSeizeTokens"
      | "liquidationIncentiveMantissa"
      | "markets"
      | "maxAssets"
      | "mintAllowed"
      | "mintGuardianPaused"
      | "mintVerify"
      | "oracle"
      | "pauseGuardian"
      | "pendingAdmin"
      | "pendingTectonicCoreImplementation"
      | "redeemAllowed"
      | "redeemVerify"
      | "repayBorrowAllowed"
      | "repayBorrowVerify"
      | "seizeAllowed"
      | "seizeGuardianPaused"
      | "seizeVerify"
      | "setTonicAddress"
      | "tectonicCoreImplementation"
      | "tokenToPerUserTvlProtectLimit"
      | "tonicAccrued"
      | "tonicBorrowState"
      | "tonicBorrowerIndex"
      | "tonicContributorSpeeds"
      | "tonicRate"
      | "tonicSpeeds"
      | "tonicSupplierIndex"
      | "tonicSupplyState"
      | "transferAllowed"
      | "transferGuardianPaused"
      | "transferVerify"
      | "updateContributorRewards"
      | "utilizedTvlAmount"
      | "whitelistProtectEnabled"
      | "whitelistedAddresses"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Failure"): EventFragment;

  encodeFunctionData(
    functionFragment: "_become",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_borrowGuardianPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_grantTonic",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_mintGuardianPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_setBorrowPaused",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_setCloseFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_setCollateralFactor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_setContributorTonicSpeed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_setLiquidationIncentive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_setMintPaused",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_setPauseGuardian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_setSeizePaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_setTonicSpeed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_setTransferPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_setWhitelistProtect",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_supportMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "accountAssets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allMarkets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowAllowed",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowCapGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowCaps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowGuardianPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowVerify",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMembership",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTonic(address[],address[],bool,bool)",
    values: [AddressLike[], AddressLike[], boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTonic(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTonic(address,address[])",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "closeFactorMantissa",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enterMarkets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "exitMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetsIn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTonicAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDeprecated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTectonicCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastContributorBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateBorrowAllowed",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateBorrowVerify",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateCalculateSeizeTokens",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationIncentiveMantissa",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "maxAssets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintAllowed",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintGuardianPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVerify",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTectonicCoreImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemAllowed",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemVerify",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayBorrowAllowed",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayBorrowVerify",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seizeAllowed",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seizeGuardianPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seizeVerify",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTonicAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tectonicCoreImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToPerUserTvlProtectLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tonicAccrued",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tonicBorrowState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tonicBorrowerIndex",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tonicContributorSpeeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "tonicRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tonicSpeeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tonicSupplierIndex",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tonicSupplyState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAllowed",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferGuardianPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferVerify",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContributorRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "utilizedTvlAmount",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistProtectEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedAddresses",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "_become", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_borrowGuardianPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_grantTonic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_mintGuardianPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setBorrowPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setCloseFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setCollateralFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setContributorTonicSpeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setLiquidationIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setMintPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setPauseGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setSeizePaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setTonicSpeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setTransferPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setWhitelistProtect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_supportMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allMarkets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowCapGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowCaps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowGuardianPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMembership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTonic(address[],address[],bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTonic(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTonic(address,address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeFactorMantissa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exitMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetsIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTonicAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDeprecated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTectonicCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastContributorBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateBorrowAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateBorrowVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateCalculateSeizeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationIncentiveMantissa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintGuardianPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintVerify", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTectonicCoreImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayBorrowAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayBorrowVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seizeAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seizeGuardianPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seizeVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTonicAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tectonicCoreImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToPerUserTvlProtectLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tonicAccrued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tonicBorrowState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tonicBorrowerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tonicContributorSpeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tonicRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tonicSpeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tonicSupplierIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tonicSupplyState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferGuardianPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContributorRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "utilizedTvlAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistProtectEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedAddresses",
    data: BytesLike
  ): Result;
}

export namespace FailureEvent {
  export type InputTuple = [
    error: BigNumberish,
    info: BigNumberish,
    detail: BigNumberish
  ];
  export type OutputTuple = [error: bigint, info: bigint, detail: bigint];
  export interface OutputObject {
    error: bigint;
    info: bigint;
    detail: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TectonicCoreImpl extends BaseContract {
  connect(runner?: ContractRunner | null): TectonicCoreImpl;
  waitForDeployment(): Promise<this>;

  interface: TectonicCoreImplInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _become: TypedContractMethod<[unitroller: AddressLike], [void], "nonpayable">;

  _borrowGuardianPaused: TypedContractMethod<[], [boolean], "view">;

  _grantTonic: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  _mintGuardianPaused: TypedContractMethod<[], [boolean], "view">;

  _setBorrowPaused: TypedContractMethod<
    [tToken: AddressLike, state: boolean],
    [boolean],
    "nonpayable"
  >;

  _setCloseFactor: TypedContractMethod<
    [newCloseFactorMantissa: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  _setCollateralFactor: TypedContractMethod<
    [tToken: AddressLike, newCollateralFactorMantissa: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  _setContributorTonicSpeed: TypedContractMethod<
    [contributor: AddressLike, tonicSpeed: BigNumberish],
    [void],
    "nonpayable"
  >;

  _setLiquidationIncentive: TypedContractMethod<
    [newLiquidationIncentiveMantissa: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  _setMintPaused: TypedContractMethod<
    [tToken: AddressLike, state: boolean],
    [boolean],
    "nonpayable"
  >;

  _setPauseGuardian: TypedContractMethod<
    [newPauseGuardian: AddressLike],
    [bigint],
    "nonpayable"
  >;

  _setPriceOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [bigint],
    "nonpayable"
  >;

  _setSeizePaused: TypedContractMethod<
    [state: boolean],
    [boolean],
    "nonpayable"
  >;

  _setTonicSpeed: TypedContractMethod<
    [tToken: AddressLike, tonicSpeed: BigNumberish],
    [void],
    "nonpayable"
  >;

  _setTransferPaused: TypedContractMethod<
    [state: boolean],
    [boolean],
    "nonpayable"
  >;

  _setWhitelistProtect: TypedContractMethod<
    [whitelistStatus: boolean],
    [void],
    "nonpayable"
  >;

  _supportMarket: TypedContractMethod<
    [tToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  accountAssets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  allMarkets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  borrowAllowed: TypedContractMethod<
    [tToken: AddressLike, borrower: AddressLike, borrowAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  borrowCapGuardian: TypedContractMethod<[], [string], "view">;

  borrowCaps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  borrowGuardianPaused: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  borrowVerify: TypedContractMethod<
    [tToken: AddressLike, borrower: AddressLike, borrowAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkMembership: TypedContractMethod<
    [account: AddressLike, tToken: AddressLike],
    [boolean],
    "view"
  >;

  "claimTonic(address[],address[],bool,bool)": TypedContractMethod<
    [
      holders: AddressLike[],
      tTokens: AddressLike[],
      borrowers: boolean,
      suppliers: boolean
    ],
    [void],
    "nonpayable"
  >;

  "claimTonic(address)": TypedContractMethod<
    [holder: AddressLike],
    [void],
    "nonpayable"
  >;

  "claimTonic(address,address[])": TypedContractMethod<
    [holder: AddressLike, tTokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  closeFactorMantissa: TypedContractMethod<[], [bigint], "view">;

  enterMarkets: TypedContractMethod<
    [tTokens: AddressLike[]],
    [bigint[]],
    "nonpayable"
  >;

  exitMarket: TypedContractMethod<
    [tToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getAllMarkets: TypedContractMethod<[], [string[]], "view">;

  getAssetsIn: TypedContractMethod<[account: AddressLike], [string[]], "view">;

  getBlockNumber: TypedContractMethod<[], [bigint], "view">;

  getTonicAddress: TypedContractMethod<[], [string], "view">;

  isDeprecated: TypedContractMethod<[tToken: AddressLike], [boolean], "view">;

  isTectonicCore: TypedContractMethod<[], [boolean], "view">;

  lastContributorBlock: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  liquidateBorrowAllowed: TypedContractMethod<
    [
      tTokenBorrowed: AddressLike,
      tTokenCollateral: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  liquidateBorrowVerify: TypedContractMethod<
    [
      tTokenBorrowed: AddressLike,
      tTokenCollateral: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish,
      seizeTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  liquidateCalculateSeizeTokens: TypedContractMethod<
    [
      tTokenBorrowed: AddressLike,
      tTokenCollateral: AddressLike,
      actualRepayAmount: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;

  liquidationIncentiveMantissa: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, boolean] & {
        isListed: boolean;
        collateralFactorMantissa: bigint;
        isTonicized: boolean;
      }
    ],
    "view"
  >;

  maxAssets: TypedContractMethod<[], [bigint], "view">;

  mintAllowed: TypedContractMethod<
    [tToken: AddressLike, minter: AddressLike, mintAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  mintGuardianPaused: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  mintVerify: TypedContractMethod<
    [
      tToken: AddressLike,
      minter: AddressLike,
      mintAmount: BigNumberish,
      mintTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  pauseGuardian: TypedContractMethod<[], [string], "view">;

  pendingAdmin: TypedContractMethod<[], [string], "view">;

  pendingTectonicCoreImplementation: TypedContractMethod<[], [string], "view">;

  redeemAllowed: TypedContractMethod<
    [tToken: AddressLike, redeemer: AddressLike, redeemTokens: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  redeemVerify: TypedContractMethod<
    [
      tToken: AddressLike,
      redeemer: AddressLike,
      redeemAmount: BigNumberish,
      redeemTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  repayBorrowAllowed: TypedContractMethod<
    [
      tToken: AddressLike,
      payer: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  repayBorrowVerify: TypedContractMethod<
    [
      tToken: AddressLike,
      payer: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish,
      borrowerIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  seizeAllowed: TypedContractMethod<
    [
      tTokenCollateral: AddressLike,
      tTokenBorrowed: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      seizeTokens: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  seizeGuardianPaused: TypedContractMethod<[], [boolean], "view">;

  seizeVerify: TypedContractMethod<
    [
      tTokenCollateral: AddressLike,
      tTokenBorrowed: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      seizeTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setTonicAddress: TypedContractMethod<
    [_tonicAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  tectonicCoreImplementation: TypedContractMethod<[], [string], "view">;

  tokenToPerUserTvlProtectLimit: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  tonicAccrued: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tonicBorrowState: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { index: bigint; block: bigint }],
    "view"
  >;

  tonicBorrowerIndex: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  tonicContributorSpeeds: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  tonicRate: TypedContractMethod<[], [bigint], "view">;

  tonicSpeeds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tonicSupplierIndex: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  tonicSupplyState: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { index: bigint; block: bigint }],
    "view"
  >;

  transferAllowed: TypedContractMethod<
    [
      tToken: AddressLike,
      src: AddressLike,
      dst: AddressLike,
      transferTokens: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  transferGuardianPaused: TypedContractMethod<[], [boolean], "view">;

  transferVerify: TypedContractMethod<
    [
      tToken: AddressLike,
      src: AddressLike,
      dst: AddressLike,
      transferTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateContributorRewards: TypedContractMethod<
    [contributor: AddressLike],
    [void],
    "nonpayable"
  >;

  utilizedTvlAmount: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  whitelistProtectEnabled: TypedContractMethod<[], [boolean], "view">;

  whitelistedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_become"
  ): TypedContractMethod<[unitroller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "_borrowGuardianPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "_grantTonic"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_mintGuardianPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "_setBorrowPaused"
  ): TypedContractMethod<
    [tToken: AddressLike, state: boolean],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setCloseFactor"
  ): TypedContractMethod<
    [newCloseFactorMantissa: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setCollateralFactor"
  ): TypedContractMethod<
    [tToken: AddressLike, newCollateralFactorMantissa: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setContributorTonicSpeed"
  ): TypedContractMethod<
    [contributor: AddressLike, tonicSpeed: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setLiquidationIncentive"
  ): TypedContractMethod<
    [newLiquidationIncentiveMantissa: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setMintPaused"
  ): TypedContractMethod<
    [tToken: AddressLike, state: boolean],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setPauseGuardian"
  ): TypedContractMethod<
    [newPauseGuardian: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setPriceOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "_setSeizePaused"
  ): TypedContractMethod<[state: boolean], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "_setTonicSpeed"
  ): TypedContractMethod<
    [tToken: AddressLike, tonicSpeed: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_setTransferPaused"
  ): TypedContractMethod<[state: boolean], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "_setWhitelistProtect"
  ): TypedContractMethod<[whitelistStatus: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "_supportMarket"
  ): TypedContractMethod<[tToken: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "accountAssets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allMarkets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "borrowAllowed"
  ): TypedContractMethod<
    [tToken: AddressLike, borrower: AddressLike, borrowAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrowCapGuardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowCaps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowGuardianPaused"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "borrowVerify"
  ): TypedContractMethod<
    [tToken: AddressLike, borrower: AddressLike, borrowAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkMembership"
  ): TypedContractMethod<
    [account: AddressLike, tToken: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimTonic(address[],address[],bool,bool)"
  ): TypedContractMethod<
    [
      holders: AddressLike[],
      tTokens: AddressLike[],
      borrowers: boolean,
      suppliers: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimTonic(address)"
  ): TypedContractMethod<[holder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTonic(address,address[])"
  ): TypedContractMethod<
    [holder: AddressLike, tTokens: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeFactorMantissa"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enterMarkets"
  ): TypedContractMethod<[tTokens: AddressLike[]], [bigint[]], "nonpayable">;
  getFunction(
    nameOrSignature: "exitMarket"
  ): TypedContractMethod<[tToken: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllMarkets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAssetsIn"
  ): TypedContractMethod<[account: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBlockNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTonicAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isDeprecated"
  ): TypedContractMethod<[tToken: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTectonicCore"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastContributorBlock"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidateBorrowAllowed"
  ): TypedContractMethod<
    [
      tTokenBorrowed: AddressLike,
      tTokenCollateral: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidateBorrowVerify"
  ): TypedContractMethod<
    [
      tTokenBorrowed: AddressLike,
      tTokenCollateral: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish,
      seizeTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidateCalculateSeizeTokens"
  ): TypedContractMethod<
    [
      tTokenBorrowed: AddressLike,
      tTokenCollateral: AddressLike,
      actualRepayAmount: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidationIncentiveMantissa"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, boolean] & {
        isListed: boolean;
        collateralFactorMantissa: bigint;
        isTonicized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintAllowed"
  ): TypedContractMethod<
    [tToken: AddressLike, minter: AddressLike, mintAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintGuardianPaused"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintVerify"
  ): TypedContractMethod<
    [
      tToken: AddressLike,
      minter: AddressLike,
      mintAmount: BigNumberish,
      mintTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseGuardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingTectonicCoreImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeemAllowed"
  ): TypedContractMethod<
    [tToken: AddressLike, redeemer: AddressLike, redeemTokens: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemVerify"
  ): TypedContractMethod<
    [
      tToken: AddressLike,
      redeemer: AddressLike,
      redeemAmount: BigNumberish,
      redeemTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayBorrowAllowed"
  ): TypedContractMethod<
    [
      tToken: AddressLike,
      payer: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayBorrowVerify"
  ): TypedContractMethod<
    [
      tToken: AddressLike,
      payer: AddressLike,
      borrower: AddressLike,
      repayAmount: BigNumberish,
      borrowerIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "seizeAllowed"
  ): TypedContractMethod<
    [
      tTokenCollateral: AddressLike,
      tTokenBorrowed: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      seizeTokens: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "seizeGuardianPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "seizeVerify"
  ): TypedContractMethod<
    [
      tTokenCollateral: AddressLike,
      tTokenBorrowed: AddressLike,
      liquidator: AddressLike,
      borrower: AddressLike,
      seizeTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTonicAddress"
  ): TypedContractMethod<[_tonicAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tectonicCoreImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenToPerUserTvlProtectLimit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tonicAccrued"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tonicBorrowState"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { index: bigint; block: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "tonicBorrowerIndex"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tonicContributorSpeeds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tonicRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tonicSpeeds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tonicSupplierIndex"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tonicSupplyState"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { index: bigint; block: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferAllowed"
  ): TypedContractMethod<
    [
      tToken: AddressLike,
      src: AddressLike,
      dst: AddressLike,
      transferTokens: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferGuardianPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferVerify"
  ): TypedContractMethod<
    [
      tToken: AddressLike,
      src: AddressLike,
      dst: AddressLike,
      transferTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateContributorRewards"
  ): TypedContractMethod<[contributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "utilizedTvlAmount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelistProtectEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "Failure"
  ): TypedContractEvent<
    FailureEvent.InputTuple,
    FailureEvent.OutputTuple,
    FailureEvent.OutputObject
  >;

  filters: {
    "Failure(uint256,uint256,uint256)": TypedContractEvent<
      FailureEvent.InputTuple,
      FailureEvent.OutputTuple,
      FailureEvent.OutputObject
    >;
    Failure: TypedContractEvent<
      FailureEvent.InputTuple,
      FailureEvent.OutputTuple,
      FailureEvent.OutputObject
    >;
  };
}
