/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TDelegateInterface } from "./TDelegateInterface";
export type { TDelegationStorage } from "./TDelegationStorage";
export type { TDelegatorInterface } from "./TDelegatorInterface";
export type { TErc20Interface } from "./TErc20Interface";
export type { TErc20Storage } from "./TErc20Storage";
export type { TTokenInterface } from "./TTokenInterface";
export type { TTokenStorage } from "./TTokenStorage";
