/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errorReporterSol from "./ErrorReporter.sol";
export type { errorReporterSol };
import type * as tTokenInterfacesSol from "./TTokenInterfaces.sol";
export type { tTokenInterfacesSol };
import type * as tectonicCoreSol from "./TectonicCore.sol";
export type { tectonicCoreSol };
import type * as tectonicCoreStorageSol from "./TectonicCoreStorage.sol";
export type { tectonicCoreStorageSol };
export type { EIP20Interface } from "./EIP20Interface";
export type { EIP20NonStandardInterface } from "./EIP20NonStandardInterface";
export type { InterestRateModel } from "./InterestRateModel";
export type { JumpRateModel } from "./JumpRateModel";
export type { MockInterestRateModel } from "./MockInterestRateModel";
export type { PriceOracle } from "./PriceOracle";
export type { SimplePriceOracle } from "./SimplePriceOracle";
export type { TErc20Delegate } from "./TErc20Delegate";
export type { TErc20Delegator } from "./TErc20Delegator";
export type { TToken } from "./TToken";
export type { TectonicCoreInterface } from "./TectonicCoreInterface";
export type { TectonicCoreTest } from "./TectonicCoreTest";
export type { TectonicSocket } from "./TectonicSocket";
export type { TectonicSocketInterface } from "./TectonicSocketInterface";
export type { Tonic } from "./Tonic";
