/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SimplePriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getUnderlyingPrice"
      | "isPriceOracle"
      | "prices"
      | "setUnderlyingPrice"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PricePosted"): EventFragment;

  encodeFunctionData(
    functionFragment: "getUnderlyingPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "prices", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setUnderlyingPrice",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getUnderlyingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "prices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUnderlyingPrice",
    data: BytesLike
  ): Result;
}

export namespace PricePostedEvent {
  export type InputTuple = [
    asset: AddressLike,
    previousPriceMantissa: BigNumberish,
    requestedPriceMantissa: BigNumberish,
    newPriceMantissa: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    previousPriceMantissa: bigint,
    requestedPriceMantissa: bigint,
    newPriceMantissa: bigint
  ];
  export interface OutputObject {
    asset: string;
    previousPriceMantissa: bigint;
    requestedPriceMantissa: bigint;
    newPriceMantissa: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimplePriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): SimplePriceOracle;
  waitForDeployment(): Promise<this>;

  interface: SimplePriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getUnderlyingPrice: TypedContractMethod<
    [tToken: AddressLike],
    [bigint],
    "view"
  >;

  isPriceOracle: TypedContractMethod<[], [boolean], "view">;

  prices: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setUnderlyingPrice: TypedContractMethod<
    [tToken: AddressLike, underlyingPriceMantissa: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getUnderlyingPrice"
  ): TypedContractMethod<[tToken: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPriceOracle"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "prices"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setUnderlyingPrice"
  ): TypedContractMethod<
    [tToken: AddressLike, underlyingPriceMantissa: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PricePosted"
  ): TypedContractEvent<
    PricePostedEvent.InputTuple,
    PricePostedEvent.OutputTuple,
    PricePostedEvent.OutputObject
  >;

  filters: {
    "PricePosted(address,uint256,uint256,uint256)": TypedContractEvent<
      PricePostedEvent.InputTuple,
      PricePostedEvent.OutputTuple,
      PricePostedEvent.OutputObject
    >;
    PricePosted: TypedContractEvent<
      PricePostedEvent.InputTuple,
      PricePostedEvent.OutputTuple,
      PricePostedEvent.OutputObject
    >;
  };
}
