/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tectonic from "./tectonic";
export type { tectonic };
export type { MockERC20 } from "./MockERC20";
export type { MockVault } from "./MockVault";
