/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockVault__factory>;
    getContractFactory(
      name: "EIP20Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP20Interface__factory>;
    getContractFactory(
      name: "EIP20NonStandardInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP20NonStandardInterface__factory>;
    getContractFactory(
      name: "TectonicCoreErrorReporter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreErrorReporter__factory>;
    getContractFactory(
      name: "TokenErrorReporter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenErrorReporter__factory>;
    getContractFactory(
      name: "InterestRateModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InterestRateModel__factory>;
    getContractFactory(
      name: "JumpRateModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JumpRateModel__factory>;
    getContractFactory(
      name: "MockInterestRateModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockInterestRateModel__factory>;
    getContractFactory(
      name: "PriceOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PriceOracle__factory>;
    getContractFactory(
      name: "SimplePriceOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimplePriceOracle__factory>;
    getContractFactory(
      name: "TectonicCoreImpl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreImpl__factory>;
    getContractFactory(
      name: "TectonicCoreInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreInterface__factory>;
    getContractFactory(
      name: "TectonicCoreStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreStorage__factory>;
    getContractFactory(
      name: "TectonicCoreV1Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreV1Storage__factory>;
    getContractFactory(
      name: "TectonicCoreV2Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreV2Storage__factory>;
    getContractFactory(
      name: "TectonicCoreV3Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreV3Storage__factory>;
    getContractFactory(
      name: "TectonicCoreV4Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreV4Storage__factory>;
    getContractFactory(
      name: "TectonicCoreV5Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreV5Storage__factory>;
    getContractFactory(
      name: "TectonicCoreV6Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreV6Storage__factory>;
    getContractFactory(
      name: "TectonicSocketAdminStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicSocketAdminStorage__factory>;
    getContractFactory(
      name: "TectonicCoreTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicCoreTest__factory>;
    getContractFactory(
      name: "TectonicSocket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicSocket__factory>;
    getContractFactory(
      name: "TectonicSocketInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TectonicSocketInterface__factory>;
    getContractFactory(
      name: "TErc20Delegate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TErc20Delegate__factory>;
    getContractFactory(
      name: "TErc20Delegator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TErc20Delegator__factory>;
    getContractFactory(
      name: "Tonic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Tonic__factory>;
    getContractFactory(
      name: "TToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TToken__factory>;
    getContractFactory(
      name: "TDelegateInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TDelegateInterface__factory>;
    getContractFactory(
      name: "TDelegationStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TDelegationStorage__factory>;
    getContractFactory(
      name: "TDelegatorInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TDelegatorInterface__factory>;
    getContractFactory(
      name: "TErc20Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TErc20Interface__factory>;
    getContractFactory(
      name: "TErc20Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TErc20Storage__factory>;
    getContractFactory(
      name: "TTokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TTokenInterface__factory>;
    getContractFactory(
      name: "TTokenStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TTokenStorage__factory>;

    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockVault>;
    getContractAt(
      name: "EIP20Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP20Interface>;
    getContractAt(
      name: "EIP20NonStandardInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP20NonStandardInterface>;
    getContractAt(
      name: "TectonicCoreErrorReporter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreErrorReporter>;
    getContractAt(
      name: "TokenErrorReporter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenErrorReporter>;
    getContractAt(
      name: "InterestRateModel",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InterestRateModel>;
    getContractAt(
      name: "JumpRateModel",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.JumpRateModel>;
    getContractAt(
      name: "MockInterestRateModel",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockInterestRateModel>;
    getContractAt(
      name: "PriceOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PriceOracle>;
    getContractAt(
      name: "SimplePriceOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimplePriceOracle>;
    getContractAt(
      name: "TectonicCoreImpl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreImpl>;
    getContractAt(
      name: "TectonicCoreInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreInterface>;
    getContractAt(
      name: "TectonicCoreStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreStorage>;
    getContractAt(
      name: "TectonicCoreV1Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreV1Storage>;
    getContractAt(
      name: "TectonicCoreV2Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreV2Storage>;
    getContractAt(
      name: "TectonicCoreV3Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreV3Storage>;
    getContractAt(
      name: "TectonicCoreV4Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreV4Storage>;
    getContractAt(
      name: "TectonicCoreV5Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreV5Storage>;
    getContractAt(
      name: "TectonicCoreV6Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreV6Storage>;
    getContractAt(
      name: "TectonicSocketAdminStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicSocketAdminStorage>;
    getContractAt(
      name: "TectonicCoreTest",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicCoreTest>;
    getContractAt(
      name: "TectonicSocket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicSocket>;
    getContractAt(
      name: "TectonicSocketInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TectonicSocketInterface>;
    getContractAt(
      name: "TErc20Delegate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TErc20Delegate>;
    getContractAt(
      name: "TErc20Delegator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TErc20Delegator>;
    getContractAt(
      name: "Tonic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Tonic>;
    getContractAt(
      name: "TToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TToken>;
    getContractAt(
      name: "TDelegateInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TDelegateInterface>;
    getContractAt(
      name: "TDelegationStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TDelegationStorage>;
    getContractAt(
      name: "TDelegatorInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TDelegatorInterface>;
    getContractAt(
      name: "TErc20Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TErc20Interface>;
    getContractAt(
      name: "TErc20Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TErc20Storage>;
    getContractAt(
      name: "TTokenInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TTokenInterface>;
    getContractAt(
      name: "TTokenStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TTokenStorage>;

    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockVault>;
    deployContract(
      name: "EIP20Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP20Interface>;
    deployContract(
      name: "EIP20NonStandardInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP20NonStandardInterface>;
    deployContract(
      name: "TectonicCoreErrorReporter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreErrorReporter>;
    deployContract(
      name: "TokenErrorReporter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenErrorReporter>;
    deployContract(
      name: "InterestRateModel",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InterestRateModel>;
    deployContract(
      name: "JumpRateModel",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.JumpRateModel>;
    deployContract(
      name: "MockInterestRateModel",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockInterestRateModel>;
    deployContract(
      name: "PriceOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceOracle>;
    deployContract(
      name: "SimplePriceOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimplePriceOracle>;
    deployContract(
      name: "TectonicCoreImpl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreImpl>;
    deployContract(
      name: "TectonicCoreInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreInterface>;
    deployContract(
      name: "TectonicCoreStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreStorage>;
    deployContract(
      name: "TectonicCoreV1Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV1Storage>;
    deployContract(
      name: "TectonicCoreV2Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV2Storage>;
    deployContract(
      name: "TectonicCoreV3Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV3Storage>;
    deployContract(
      name: "TectonicCoreV4Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV4Storage>;
    deployContract(
      name: "TectonicCoreV5Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV5Storage>;
    deployContract(
      name: "TectonicCoreV6Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV6Storage>;
    deployContract(
      name: "TectonicSocketAdminStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicSocketAdminStorage>;
    deployContract(
      name: "TectonicCoreTest",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreTest>;
    deployContract(
      name: "TectonicSocket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicSocket>;
    deployContract(
      name: "TectonicSocketInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicSocketInterface>;
    deployContract(
      name: "TErc20Delegate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Delegate>;
    deployContract(
      name: "TErc20Delegator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Delegator>;
    deployContract(
      name: "Tonic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Tonic>;
    deployContract(
      name: "TToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TToken>;
    deployContract(
      name: "TDelegateInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TDelegateInterface>;
    deployContract(
      name: "TDelegationStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TDelegationStorage>;
    deployContract(
      name: "TDelegatorInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TDelegatorInterface>;
    deployContract(
      name: "TErc20Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Interface>;
    deployContract(
      name: "TErc20Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Storage>;
    deployContract(
      name: "TTokenInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TTokenInterface>;
    deployContract(
      name: "TTokenStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TTokenStorage>;

    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockVault>;
    deployContract(
      name: "EIP20Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP20Interface>;
    deployContract(
      name: "EIP20NonStandardInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP20NonStandardInterface>;
    deployContract(
      name: "TectonicCoreErrorReporter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreErrorReporter>;
    deployContract(
      name: "TokenErrorReporter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenErrorReporter>;
    deployContract(
      name: "InterestRateModel",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InterestRateModel>;
    deployContract(
      name: "JumpRateModel",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.JumpRateModel>;
    deployContract(
      name: "MockInterestRateModel",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockInterestRateModel>;
    deployContract(
      name: "PriceOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceOracle>;
    deployContract(
      name: "SimplePriceOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimplePriceOracle>;
    deployContract(
      name: "TectonicCoreImpl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreImpl>;
    deployContract(
      name: "TectonicCoreInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreInterface>;
    deployContract(
      name: "TectonicCoreStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreStorage>;
    deployContract(
      name: "TectonicCoreV1Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV1Storage>;
    deployContract(
      name: "TectonicCoreV2Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV2Storage>;
    deployContract(
      name: "TectonicCoreV3Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV3Storage>;
    deployContract(
      name: "TectonicCoreV4Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV4Storage>;
    deployContract(
      name: "TectonicCoreV5Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV5Storage>;
    deployContract(
      name: "TectonicCoreV6Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreV6Storage>;
    deployContract(
      name: "TectonicSocketAdminStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicSocketAdminStorage>;
    deployContract(
      name: "TectonicCoreTest",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicCoreTest>;
    deployContract(
      name: "TectonicSocket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicSocket>;
    deployContract(
      name: "TectonicSocketInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TectonicSocketInterface>;
    deployContract(
      name: "TErc20Delegate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Delegate>;
    deployContract(
      name: "TErc20Delegator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Delegator>;
    deployContract(
      name: "Tonic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Tonic>;
    deployContract(
      name: "TToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TToken>;
    deployContract(
      name: "TDelegateInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TDelegateInterface>;
    deployContract(
      name: "TDelegationStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TDelegationStorage>;
    deployContract(
      name: "TDelegatorInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TDelegatorInterface>;
    deployContract(
      name: "TErc20Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Interface>;
    deployContract(
      name: "TErc20Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TErc20Storage>;
    deployContract(
      name: "TTokenInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TTokenInterface>;
    deployContract(
      name: "TTokenStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TTokenStorage>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
