/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TectonicCoreErrorReporter,
  TectonicCoreErrorReporterInterface,
} from "../../../../contracts/tectonic/ErrorReporter.sol/TectonicCoreErrorReporter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "error",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "info",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "detail",
        type: "uint256",
      },
    ],
    name: "Failure",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052600080fdfea265627a7a72315820af38e7d544aea9c881721b39af06c236daf272ac530200c44b343827573f67dd64736f6c63430005100032";

type TectonicCoreErrorReporterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TectonicCoreErrorReporterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TectonicCoreErrorReporter__factory extends ContractFactory {
  constructor(...args: TectonicCoreErrorReporterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TectonicCoreErrorReporter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TectonicCoreErrorReporter__factory {
    return super.connect(runner) as TectonicCoreErrorReporter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TectonicCoreErrorReporterInterface {
    return new Interface(_abi) as TectonicCoreErrorReporterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TectonicCoreErrorReporter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TectonicCoreErrorReporter;
  }
}
