/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TectonicCoreStorage } from "./TectonicCoreStorage";
export type { TectonicCoreV1Storage } from "./TectonicCoreV1Storage";
export type { TectonicCoreV2Storage } from "./TectonicCoreV2Storage";
export type { TectonicCoreV3Storage } from "./TectonicCoreV3Storage";
export type { TectonicCoreV4Storage } from "./TectonicCoreV4Storage";
export type { TectonicCoreV5Storage } from "./TectonicCoreV5Storage";
export type { TectonicCoreV6Storage } from "./TectonicCoreV6Storage";
export type { TectonicSocketAdminStorage } from "./TectonicSocketAdminStorage";
