/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TDelegateInterface__factory } from "./TDelegateInterface__factory";
export { TDelegationStorage__factory } from "./TDelegationStorage__factory";
export { TDelegatorInterface__factory } from "./TDelegatorInterface__factory";
export { TErc20Interface__factory } from "./TErc20Interface__factory";
export { TErc20Storage__factory } from "./TErc20Storage__factory";
export { TTokenInterface__factory } from "./TTokenInterface__factory";
export { TTokenStorage__factory } from "./TTokenStorage__factory";
