/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TDelegatorInterface,
  TDelegatorInterfaceInterface,
} from "../../../../contracts/tectonic/TTokenInterfaces.sol/TDelegatorInterface";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldImplementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
    ],
    name: "NewImplementation",
    type: "event",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "implementation_",
        type: "address",
      },
      {
        internalType: "bool",
        name: "allowResign",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "becomeImplementationData",
        type: "bytes",
      },
    ],
    name: "_setImplementation",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TDelegatorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): TDelegatorInterfaceInterface {
    return new Interface(_abi) as TDelegatorInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TDelegatorInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TDelegatorInterface;
  }
}
