/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TDelegateInterface,
  TDelegateInterfaceInterface,
} from "../../../../contracts/tectonic/TTokenInterfaces.sol/TDelegateInterface";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "_becomeImplementation",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "_resignImplementation",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TDelegateInterface__factory {
  static readonly abi = _abi;
  static createInterface(): TDelegateInterfaceInterface {
    return new Interface(_abi) as TDelegateInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TDelegateInterface {
    return new Contract(address, _abi, runner) as unknown as TDelegateInterface;
  }
}
